## This first function creates a list object containing an invertible matrix
## along with functions to re-set or get the matrix, as well as (re-)set and get
## its inverse. It does not calculate the inverse.

## The second function checks if an inverse has already been calculated. If it
## does not exist it calculates the matrix inverse and caches it, otherwise it
## returns the cached inverse.



## makeCacheMatrix takes a matrix as an input and stores it along with set and get
## functions for the input and its inverse.

makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
        set <- function(y) {
                x <<- y
                inv <<- NULL
        }
        get <- function() x
        setinv <- function(xinv) inv <<- xinv
        getinv <- function() inv
        list(set = set, get = get,
             setinv = setinv,
             getinv = getinv)
}


## cacheSolve expects an object generated by the makeCacheMatrix funtion as an input,
## then either returns a cached matrix inverse or, if no cahced inverse is found,
## calculates and caches the inverse.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        inv <- x$getinv()
        if(!is.null(inv)) {
                message("getting cached data")
                return(inv)
        }
        data <- x$get()
        inv <- solve(data, ...)
        x$setinv(inv)
        inv
}